name: buildEnv_runPython

on:
  schedule:
    - cron: '0 16 * * *'  # UTC 16:00 = 北京时间 0:00（次日）

  workflow_dispatch:  # 支持手动触发

  repository_dispatch:
    types: [trigger-from-MySubconverterRemoteConfig]

  push:
    branches:
      - main  # 每次push到main分支时触发

jobs:
  buildEnv_runPython:
    runs-on: ubuntu-latest  # 指定运行环境
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # 检出仓库代码

      # tindy2013  asdlokj1qpi233
      - name: Extract and run subconverter
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}  # 设置环境变量
        run: |
          curl -L -o subconverter_linux64.tar.gz $(curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $PERSONAL_TOKEN" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/tindy2013/subconverter/releases/latest | grep "browser_download_url" | grep "linux64[.]tar" | cut -d '"' -f 4)
          tar xzf subconverter_linux64.tar.gz
          chmod +x subconverter/subconverter
          nohup subconverter/subconverter &
      
      # # 使用docker的subconverter，会保持最新版本
      # # tindy2013/subconverter  asdlokj1qpi23/subconverter
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3
      # - name: Run Docker container
      #   run: |
      #     docker run -d --restart=always -p 25500:25500 asdlokj1qpi23/subconverter:latest

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pyyaml

      - name: runrun python
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_ACCOUNT_API_TOKEN: ${{ secrets.CF_ACCOUNT_API_TOKEN }}
          CF_KV_ID: ${{ secrets.CF_KV_ID }}
          CONVERT_PARAM: ${{ secrets.CONVERT_PARAM }}
          # PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          # GIST_ID: ${{ secrets.GIST_ID }}
        run: python converter_push.py
